server:
  port: 5000

spring:
  cloud:
    config:
      name: config-server
      server:
        git:
          uri: https://github.com/JaseG256/Msa-Service.git
          search-paths: config-files*